# Generated by Django 4.2.16 on 2026-08-27 17:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_name', models.CharField(max_length=120)),
                ('account_type', models.CharField(choices=[('BANK', 'Bank'), ('CASH', 'Cash'), ('CREDIT_CARD', 'Credit Card'), ('WALLET', 'Wallet'), ('INVESTMENT', 'Investment'), ('OTHER', 'Other')], default='BANK', max_length=20)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['account_name'],
            },
        ),
    ]
