# Generated by Django 4.2.16 on 2026-08-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detection_method', models.CharField(choices=[('ZSCORE', 'Z-Score'), ('IQR', 'Interquartile Range'), ('ISOLATION_FOREST', 'Isolation Forest')], max_length=20)),
                ('anomaly_score', models.FloatField(help_text='Lower = more anomalous (engine convention).')),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=10)),
                ('reason', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('category', models.CharField(blank=True, default='', max_length=80)),
                ('merchant', models.CharField(blank=True, default='', max_length=120)),
                ('transaction_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('REVIEWED', 'Reviewed'), ('IGNORED', 'Ignored')], default='OPEN', max_length=10)),
                ('reviewed', models.BooleanField(default=False)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['anomaly_score', '-detected_at'],
            },
        ),
    ]
