# Generated by Django 4.2.16 on 2026-08-27 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0001_initial'),
        ('anomalies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anomaly',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anomalies', to='transactions.transaction'),
        ),
    ]
