# Generated by Django 4.2.16 on 2026-08-27 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anomalies', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anomaly',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='anomaly',
            index=models.Index(fields=['user', 'status'], name='anomalies_a_user_id_2395ec_idx'),
        ),
        migrations.AddIndex(
            model_name='anomaly',
            index=models.Index(fields=['user', 'severity'], name='anomalies_a_user_id_fca6ca_idx'),
        ),
        migrations.AddConstraint(
            model_name='anomaly',
            constraint=models.UniqueConstraint(fields=('user', 'transaction', 'detection_method'), name='uniq_anomaly_per_txn_method'),
        ),
    ]
